FROM node:18-alpine

WORKDIR /app

# Copia os arquivos de configuração
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o código fonte
COPY . .

# Expõe a porta 3001
EXPOSE 3001

# Inicia a aplicação
CMD ["npm", "start"]